Repository yenhsuan/js-data-structure, pull requests merged in 2019-01, with the labels that each got.

#8 Kimy/stack
  src/data_structures/stack.js
  src/index.js
  test/data_structures/stack.test.js
Labels: Status: Reviewed, Type: Feature

#10 Kimy/stack
  src/data_structures/stack.js
  test/data_structures/stack.test.js
Labels: Status: Review Needed, Type: Feature

#11 [Data Structure] Add Heap
  src/data_structures/heap.js
  src/utils/errors.js
  test/data_structures/heap.test.js
Labels: Status: Test Needed, Type: Feature

#12 [Refactor] Heap
  src/data_structures/heap.js
  test/data_structures/heap.test.js
Labels: Type: Refactoring

#13 [Data Structure] Add PriorityQueue
  src/data_structures/max-heap.js
  src/data_structures/min-heap.js
  src/data_structures/priority-queue.js
  src/utils/errors.js
  test/data_structures/max-heap.test.js
  test/data_structures/min-heap.test.js
  test/data_structures/priority-queue.test.js
Labels: Type: Feature
